"""
rheo_db.py
==========

A small SQLite + Python analysis helper for rheology flow-curve data.

Core features (per your spec):
- Store experiments + raw rows (CSV/XLSX exported by rheometer)
- Detect up/down ramps (if present)
- Produce plots:
  Fig1: shear rate vs shear stress
  Fig2: shear rate vs viscosity
  Fig3: shear rate vs shear stress + partial-yield compatibility markers/band
  Fig4: r0/r2 vs shear rate (wide-gap Couette / vane-in-cup interpretation)

- Fit models (separate up/down if present):
  Herschel–Bulkley: τ = τy + K γ̇^n
  Cross: η = η∞ + (η0 - η∞)/(1 + (τ/τc)^m)
  Ellis: η = η0/(1 + (τ/τc)^m)
  For HB, tau_y initial guess uses the experiment's "yield_stress0_Pa"

- Hysteresis area (if up & down):
  A = ∫ |τ_up(γ̇) - τ_down(γ̇)| dγ̇  (numeric, after interpolation)

Partial yield compatibility (wide-gap Couette / vane-in-cup):
- Stress distribution: τ(r) = τ1 (r1/r)^2
- Outer wall stress: τ2 = τ1 (r1/r2)^2
- Partially yielded annulus expected if τ2 < τy  ⇔  τ1 < τ1,c
- Critical inner-wall stress:
    τ1,c = τy (r2/r1)^2

- Yielded radius r0 defined by τ(r0)=τy:
    r0 = r1 * sqrt(τ1/τy)
  and r0 is capped by r2 (if fully yielded): r0 = min(r2, r1*sqrt(τ1/τy))

Then plot r0/r2 vs γ̇ (Fig4).

Author: generated by ChatGPT
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Optional, Tuple, List, Any

import math
import re
import sqlite3
import datetime as _dt

import numpy as np
import pandas as pd
from scipy.optimize import curve_fit
import matplotlib.pyplot as plt
from matplotlib.patches import Circle, FancyArrowPatch, Wedge


# ----------------------------
# Database helpers
# ----------------------------

def connect(db_path: str | Path) -> sqlite3.Connection:
    conn = sqlite3.connect(str(db_path))
    conn.execute("PRAGMA foreign_keys = ON;")
    return conn


def init_db(db_path: str | Path, schema_path: str | Path) -> None:
    """Create tables if they don't exist and upgrade older DBs when needed."""
    db_path = Path(db_path)
    schema_path = Path(schema_path)
    conn = connect(db_path)
    try:
        sql = schema_path.read_text(encoding="utf-8")
        conn.executescript(sql)
        _ensure_fit_results_columns(conn)
        conn.commit()
    finally:
        conn.close()


def _ensure_fit_results_columns(conn: sqlite3.Connection) -> None:
    """Add Cross/Ellis columns if an older database already has fit_results.

    SQLite cannot add multiple columns in one ALTER statement, so we add them
    one by one. Older, now-unused fit columns may remain in existing databases,
    but the app no longer writes or displays removed models.
    """
    existing = {row[1] for row in conn.execute("PRAGMA table_info(fit_results)").fetchall()}
    required = {
        "eta0_Pa_s": "REAL",
        "eta_inf_Pa_s": "REAL",
        "sigma_c_Pa": "REAL",
        "m": "REAL",
    }
    for name, typ in required.items():
        if name not in existing:
            conn.execute(f"ALTER TABLE fit_results ADD COLUMN {name} {typ}")


# ----------------------------
# IO: read and normalize raw export files
# ----------------------------

def _norm_header(s: str) -> str:
    s = str(s).strip().lower()
    # normalize degree symbol variants
    s = s.replace("℃", "c").replace("°c", "c").replace("°", "")
    # remove common separators/units punctuation
    s = re.sub(r"[ \t\n\r/·\-\(\)\[\]\{\}:;%]", "", s)
    return s


def normalize_columns(df: pd.DataFrame) -> pd.DataFrame:
    """
    Map a rheometer-export dataframe to canonical columns used by this project.
    Expected raw headers include (English):
      Shear Rate 1/s, Shear Stress Pa, Viscosity Pas, Target Shear Rate 1/s,
      Percentage Deviation %, Temperature ℃, Time s, Thrust g, Accumulated Time s,
      Torque Nm, Angular Velocity rad/s, Notes
    """
    col_map: Dict[str, str] = {}
    for c in df.columns:
        k = _norm_header(c)
        target = None
        if ("target" in k and "shearrate" in k) or (k.startswith("target") and "rate" in k):
            target = "target_shear_rate_1_s"
        elif "shearrate" in k and "target" not in k:
            target = "shear_rate_1_s"
        elif "shearstress" in k:
            target = "shear_stress_Pa"
        elif "viscosity" in k:
            target = "viscosity_Pa_s"
        elif "deviation" in k:
            target = "percentage_deviation_pct"
        elif "temperature" in k:
            target = "temperature_C"
        elif k == "times" or k.startswith("time"):
            # "Time s"
            target = "time_s"
        elif "thrust" in k:
            target = "thrust_g"
        elif "accumulated" in k and "time" in k:
            target = "accumulated_time_s"
        elif "torque" in k:
            target = "torque_Nm"
        elif "angularvelocity" in k:
            target = "angular_velocity_rad_s"
        elif "notes" in k:
            target = "notes"

        if target is not None:
            col_map[c] = target

    df = df.rename(columns=col_map).copy()

    # Ensure all expected columns exist (missing => filled with NaN)
    expected = [
        "shear_rate_1_s",
        "shear_stress_Pa",
        "viscosity_Pa_s",
        "target_shear_rate_1_s",
        "percentage_deviation_pct",
        "temperature_C",
        "time_s",
        "thrust_g",
        "accumulated_time_s",
        "torque_Nm",
        "angular_velocity_rad_s",
        "notes",
    ]
    for c in expected:
        if c not in df.columns:
            df[c] = np.nan

    # Coerce numeric columns
    numeric_cols = [c for c in expected if c not in ("notes",)]
    for c in numeric_cols:
        df[c] = pd.to_numeric(df[c], errors="coerce")

    # Notes as string
    df["notes"] = df["notes"].astype(str).where(~df["notes"].isna(), "")
    return df[expected]


def read_data_file(path: str | Path, sheet_name: str | int | None = 0) -> pd.DataFrame:
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(path)

    if path.suffix.lower() in [".xlsx", ".xls"]:
        df = pd.read_excel(path, sheet_name=sheet_name)
    else:
        # auto-sep sniffing
        df = pd.read_csv(path, sep=None, engine="python")
    return df


# ----------------------------
# Insert / fetch
# ----------------------------

def insert_experiment(
    conn: sqlite3.Connection,
    sample_name: str,
    geometry: str,
    gap_m: Optional[float] = None,
    r1_m: Optional[float] = None,
    r2_m: Optional[float] = None,
    yield_stress0_Pa: Optional[float] = None,
    notes: Optional[str] = None,
) -> int:
    cur = conn.cursor()
    cur.execute(
        """
        INSERT INTO experiments(sample_name, geometry, gap_m, r1_m, r2_m, yield_stress0_Pa, notes)
        VALUES (?, ?, ?, ?, ?, ?, ?)
        """,
        (sample_name, geometry, gap_m, r1_m, r2_m, yield_stress0_Pa, notes),
    )
    return int(cur.lastrowid)


def update_experiment(
    conn: sqlite3.Connection,
    experiment_id: int,
    *,
    sample_name: str,
    geometry: str,
    gap_m: Optional[float] = None,
    r1_m: Optional[float] = None,
    r2_m: Optional[float] = None,
    yield_stress0_Pa: Optional[float] = None,
    notes: Optional[str] = None,
) -> None:
    """Update experiment metadata.

    This is useful if you imported data with the wrong geometry parameters and
    want to correct r1/r2/gap without re-importing the raw measurements.
    """
    cur = conn.cursor()
    cur.execute(
        """
        UPDATE experiments
        SET sample_name=?, geometry=?, gap_m=?, r1_m=?, r2_m=?, yield_stress0_Pa=?, notes=?
        WHERE id=?
        """,
        (sample_name, geometry, gap_m, r1_m, r2_m, yield_stress0_Pa, notes, int(experiment_id)),
    )


def insert_measurements(conn: sqlite3.Connection, experiment_id: int, df: pd.DataFrame) -> None:
    cur = conn.cursor()
    records = []
    for i, row in df.reset_index(drop=True).iterrows():
        records.append(
            (
                experiment_id,
                int(i),
                None,  # segment
                float(row["shear_rate_1_s"]) if not pd.isna(row["shear_rate_1_s"]) else None,
                float(row["shear_stress_Pa"]) if not pd.isna(row["shear_stress_Pa"]) else None,
                float(row["viscosity_Pa_s"]) if not pd.isna(row["viscosity_Pa_s"]) else None,
                float(row["target_shear_rate_1_s"]) if not pd.isna(row["target_shear_rate_1_s"]) else None,
                float(row["percentage_deviation_pct"]) if not pd.isna(row["percentage_deviation_pct"]) else None,
                float(row["temperature_C"]) if not pd.isna(row["temperature_C"]) else None,
                float(row["time_s"]) if not pd.isna(row["time_s"]) else None,
                float(row["thrust_g"]) if not pd.isna(row["thrust_g"]) else None,
                float(row["accumulated_time_s"]) if not pd.isna(row["accumulated_time_s"]) else None,
                float(row["torque_Nm"]) if not pd.isna(row["torque_Nm"]) else None,
                float(row["angular_velocity_rad_s"]) if not pd.isna(row["angular_velocity_rad_s"]) else None,
                str(row["notes"]) if row.get("notes", "") is not None else "",
            )
        )

    cur.executemany(
        """
        INSERT INTO measurements(
            experiment_id, row_index, segment,
            shear_rate_1_s, shear_stress_Pa, viscosity_Pa_s,
            target_shear_rate_1_s, percentage_deviation_pct, temperature_C,
            time_s, thrust_g, accumulated_time_s,
            torque_Nm, angular_velocity_rad_s, notes
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        records,
    )


def import_experiment(
    db_path: str | Path,
    schema_path: str | Path,
    sample_name: str,
    geometry: str,
    data_file: str | Path,
    *,
    gap_m: Optional[float] = None,
    r1_m: Optional[float] = None,
    r2_m: Optional[float] = None,
    yield_stress0_Pa: Optional[float] = None,
    notes: Optional[str] = None,
    sheet_name: str | int | None = 0,
) -> int:
    """
    Create DB if needed, insert an experiment + its raw rows.
    Returns experiment_id.
    """
    init_db(db_path, schema_path)
    raw = read_data_file(data_file, sheet_name=sheet_name)
    df = normalize_columns(raw)

    conn = connect(db_path)
    try:
        exp_id = insert_experiment(
            conn,
            sample_name=sample_name,
            geometry=geometry,
            gap_m=gap_m,
            r1_m=r1_m,
            r2_m=r2_m,
            yield_stress0_Pa=yield_stress0_Pa,
            notes=notes,
        )
        insert_measurements(conn, exp_id, df)
        conn.commit()
        return exp_id
    finally:
        conn.close()


def fetch_experiment(conn: sqlite3.Connection, experiment_id: int) -> Dict[str, Any]:
    cur = conn.cursor()
    row = cur.execute(
        "SELECT id, sample_name, geometry, gap_m, r1_m, r2_m, yield_stress0_Pa, notes, created_at FROM experiments WHERE id=?",
        (experiment_id,),
    ).fetchone()
    if row is None:
        raise KeyError(f"experiment_id {experiment_id} not found")
    keys = ["id","sample_name","geometry","gap_m","r1_m","r2_m","yield_stress0_Pa","notes","created_at"]
    return dict(zip(keys, row))


def load_measurements_df(conn: sqlite3.Connection, experiment_id: int) -> pd.DataFrame:
    df = pd.read_sql_query(
        """
        SELECT
            row_index, segment,
            shear_rate_1_s, shear_stress_Pa, viscosity_Pa_s,
            target_shear_rate_1_s, percentage_deviation_pct, temperature_C,
            time_s, thrust_g, accumulated_time_s,
            torque_Nm, angular_velocity_rad_s, notes
        FROM measurements
        WHERE experiment_id=?
        ORDER BY row_index ASC
        """,
        conn,
        params=(experiment_id,),
    )
    return df


def update_segments(conn: sqlite3.Connection, experiment_id: int, segment_by_row_index: Dict[int, str]) -> None:
    cur = conn.cursor()
    records = [(seg, experiment_id, int(idx)) for idx, seg in segment_by_row_index.items()]
    cur.executemany(
        "UPDATE measurements SET segment=? WHERE experiment_id=? AND row_index=?",
        records,
    )


# ----------------------------
# Up / down segmentation
# ----------------------------

def split_up_down(df: pd.DataFrame, min_points_each: int = 5) -> Dict[str, pd.DataFrame]:
    """
    Detect a ramp-up then ramp-down sequence.

    Strategy:
    - Prefer target_shear_rate_1_s if present, else shear_rate_1_s.
    - Find the last index of the global maximum.
    - If both sides have at least `min_points_each`, return {'up':..., 'down':...}
      otherwise return {'all':...}
    """
    x = df["target_shear_rate_1_s"].copy()
    if x.isna().all():
        x = df["shear_rate_1_s"].copy()
    x = x.ffill().bfill()

    if len(df) < 2 * min_points_each:
        return {"all": df.copy()}

    max_val = float(np.nanmax(x.values))
    if not np.isfinite(max_val):
        return {"all": df.copy()}

    idxs = np.where(np.isclose(x.values, max_val, rtol=1e-12, atol=1e-12))[0]
    if len(idxs) == 0:
        return {"all": df.copy()}
    turn = int(idxs[-1])  # last occurrence of max

    up = df.iloc[: turn + 1].copy()
    down = df.iloc[turn + 1 :].copy()

    if len(up) >= min_points_each and len(down) >= min_points_each:
        return {"up": up, "down": down}
    return {"all": df.copy()}


# ----------------------------
# Model fits
# ----------------------------

def _r2_score(y: np.ndarray, yhat: np.ndarray) -> float:
    y = np.asarray(y, dtype=float)
    yhat = np.asarray(yhat, dtype=float)
    mask = np.isfinite(y) & np.isfinite(yhat)
    y = y[mask]
    yhat = yhat[mask]
    if y.size < 2:
        return float("nan")
    ss_res = float(np.sum((y - yhat) ** 2))
    ss_tot = float(np.sum((y - np.mean(y)) ** 2))
    if ss_tot == 0:
        return float("nan")
    return 1.0 - ss_res / ss_tot


def _hb_model(gamma: np.ndarray, tauy: float, K: float, n: float) -> np.ndarray:
    return tauy + K * np.power(gamma, n)


def fit_herschel_bulkley(gamma: np.ndarray, tau: np.ndarray, tauy0: Optional[float] = None) -> Dict[str, float]:
    """
    Fit τ = τy + K γ̇^n (Herschel–Bulkley) by non-linear least squares.
    Returns tau_y_Pa, K, n, r_squared, n_points.
    """
    gamma = np.asarray(gamma, dtype=float)
    tau = np.asarray(tau, dtype=float)

    mask = (gamma > 0) & np.isfinite(gamma) & np.isfinite(tau)
    g = gamma[mask]
    t = tau[mask]
    if g.size < 4:
        return {"tau_y_Pa": float("nan"), "K": float("nan"), "n": float("nan"), "r_squared": float("nan"), "n_points": int(g.size)}

    tauy0 = float(tauy0) if (tauy0 is not None and np.isfinite(tauy0)) else float(max(0.0, np.nanmin(t)))
    if tauy0 >= float(np.nanmax(t)):
        tauy0 = float(max(0.0, np.nanmin(t) * 0.5))

    tp = t - tauy0
    mask2 = (tp > 0) & (g > 0)
    if np.sum(mask2) >= 3:
        n_guess, logK_guess = np.polyfit(np.log(g[mask2]), np.log(tp[mask2]), 1)
        K0 = float(np.exp(logK_guess))
        n0 = float(max(1e-6, n_guess))
    else:
        K0 = float(np.nanmax(np.maximum(tp, 1e-12)))
        n0 = 1.0

    p0 = [tauy0, max(1e-12, K0), max(1e-6, n0)]
    bounds = ([0.0, 0.0, 0.0], [np.inf, np.inf, np.inf])

    try:
        popt, _pcov = curve_fit(_hb_model, g, t, p0=p0, bounds=bounds, maxfev=100000)
        tauy, K, n = popt
    except Exception:
        return {"tau_y_Pa": float("nan"), "K": float("nan"), "n": float("nan"), "r_squared": float("nan"), "n_points": int(g.size)}

    t_hat = _hb_model(g, tauy, K, n)
    r2 = _r2_score(t, t_hat)
    return {"tau_y_Pa": float(tauy), "K": float(K), "n": float(n), "r_squared": float(r2), "n_points": int(g.size)}


def _cross_model_tau_eta(tau: np.ndarray, eta_inf: float, delta_eta: float, sigma_c: float, m: float) -> np.ndarray:
    """Modified Cross model written against stress: η = η∞ + (η0-η∞)/(1+(τ/τc)^m)."""
    tau = np.asarray(tau, dtype=float)
    return eta_inf + delta_eta / (1.0 + np.power(tau / sigma_c, m))


def _ellis_model_tau_eta(tau: np.ndarray, eta0: float, sigma_c: float, m: float) -> np.ndarray:
    """Ellis model: η = η0/(1+(τ/τc)^m)."""
    tau = np.asarray(tau, dtype=float)
    return eta0 / (1.0 + np.power(tau / sigma_c, m))


def _prepare_eta_tau(tau: np.ndarray, eta: np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
    tau = np.asarray(tau, dtype=float)
    eta = np.asarray(eta, dtype=float)
    mask = (tau > 0) & (eta > 0) & np.isfinite(tau) & np.isfinite(eta)
    x = tau[mask]
    y = eta[mask]
    if x.size == 0:
        return x, y
    order = np.argsort(x)
    return x[order], y[order]


def _initial_sigma_c_from_midpoint(tau: np.ndarray, eta: np.ndarray, eta0: float, eta_inf: float) -> float:
    """Pick the stress nearest the logarithmic mid-viscosity as a stable τc guess."""
    tau = np.asarray(tau, dtype=float)
    eta = np.asarray(eta, dtype=float)
    if tau.size == 0:
        return 1.0
    eta0 = max(float(eta0), 1e-12)
    eta_inf = max(float(eta_inf), 1e-12)
    mid = math.sqrt(eta0 * eta_inf) if eta0 > eta_inf else np.nanmedian(eta)
    if not np.isfinite(mid) or mid <= 0:
        mid = np.nanmedian(eta)
    idx = int(np.nanargmin(np.abs(np.log(eta) - np.log(mid))))
    guess = float(tau[idx])
    if not np.isfinite(guess) or guess <= 0:
        guess = float(np.nanmedian(tau))
    return max(guess, 1e-12)


def fit_cross(tau: np.ndarray, eta: np.ndarray) -> Dict[str, float]:
    """
    Fit modified Cross model in log-viscosity space:
        η = η∞ + (η0 - η∞)/(1 + (τ/σc)^m)

    Returns eta0_Pa_s, eta_inf_Pa_s, sigma_c_Pa, m, r_squared, n_points.
    """
    x, y = _prepare_eta_tau(tau, eta)
    if x.size < 5:
        return {"eta0_Pa_s": float("nan"), "eta_inf_Pa_s": float("nan"), "sigma_c_Pa": float("nan"), "m": float("nan"), "r_squared": float("nan"), "n_points": int(x.size)}

    eta0_guess = float(np.nanpercentile(y, 95))
    eta_inf_guess = float(max(np.nanpercentile(y, 5), 1e-12))
    if eta0_guess <= eta_inf_guess:
        eta0_guess = float(np.nanmax(y))
        eta_inf_guess = float(max(np.nanmin(y), 1e-12))
    delta_guess = max(eta0_guess - eta_inf_guess, 1e-12)
    sigma_c_guess = _initial_sigma_c_from_midpoint(x, y, eta0_guess, eta_inf_guess)
    p0 = [eta_inf_guess, delta_guess, sigma_c_guess, 2.0]
    bounds = ([0.0, 0.0, max(float(np.nanmin(x)) * 1e-6, 1e-12), 0.01], [np.inf, np.inf, max(float(np.nanmax(x)) * 1e6, 1e-12), 100.0])

    def log_model(xx, eta_inf, delta_eta, sigma_c, m):
        return np.log(np.maximum(_cross_model_tau_eta(xx, eta_inf, delta_eta, sigma_c, m), 1e-300))

    try:
        popt, _pcov = curve_fit(log_model, x, np.log(y), p0=p0, bounds=bounds, maxfev=200000)
        eta_inf, delta_eta, sigma_c, m = popt
    except Exception:
        return {"eta0_Pa_s": float("nan"), "eta_inf_Pa_s": float("nan"), "sigma_c_Pa": float("nan"), "m": float("nan"), "r_squared": float("nan"), "n_points": int(x.size)}

    yhat = _cross_model_tau_eta(x, eta_inf, delta_eta, sigma_c, m)
    r2 = _r2_score(np.log(y), np.log(np.maximum(yhat, 1e-300)))
    return {"eta0_Pa_s": float(eta_inf + delta_eta), "eta_inf_Pa_s": float(eta_inf), "sigma_c_Pa": float(sigma_c), "m": float(m), "r_squared": float(r2), "n_points": int(x.size)}


def fit_ellis(tau: np.ndarray, eta: np.ndarray) -> Dict[str, float]:
    """
    Fit Ellis model in log-viscosity space:
        η = η0/(1 + (τ/σc)^m)

    Returns eta0_Pa_s, sigma_c_Pa, m, r_squared, n_points.
    eta_inf_Pa_s is reported as 0.0 for consistency with the Cross table.
    """
    x, y = _prepare_eta_tau(tau, eta)
    if x.size < 4:
        return {"eta0_Pa_s": float("nan"), "eta_inf_Pa_s": 0.0, "sigma_c_Pa": float("nan"), "m": float("nan"), "r_squared": float("nan"), "n_points": int(x.size)}

    eta0_guess = float(np.nanpercentile(y, 95))
    sigma_c_guess = _initial_sigma_c_from_midpoint(x, y, eta0_guess, max(float(np.nanpercentile(y, 5)), 1e-12))
    p0 = [max(eta0_guess, 1e-12), sigma_c_guess, 2.0]
    bounds = ([0.0, max(float(np.nanmin(x)) * 1e-6, 1e-12), 0.01], [np.inf, max(float(np.nanmax(x)) * 1e6, 1e-12), 100.0])

    def log_model(xx, eta0, sigma_c, m):
        return np.log(np.maximum(_ellis_model_tau_eta(xx, eta0, sigma_c, m), 1e-300))

    try:
        popt, _pcov = curve_fit(log_model, x, np.log(y), p0=p0, bounds=bounds, maxfev=200000)
        eta0, sigma_c, m = popt
    except Exception:
        return {"eta0_Pa_s": float("nan"), "eta_inf_Pa_s": 0.0, "sigma_c_Pa": float("nan"), "m": float("nan"), "r_squared": float("nan"), "n_points": int(x.size)}

    yhat = _ellis_model_tau_eta(x, eta0, sigma_c, m)
    r2 = _r2_score(np.log(y), np.log(np.maximum(yhat, 1e-300)))
    return {"eta0_Pa_s": float(eta0), "eta_inf_Pa_s": 0.0, "sigma_c_Pa": float(sigma_c), "m": float(m), "r_squared": float(r2), "n_points": int(x.size)}


# ----------------------------
# Derived metrics
# ----------------------------

def compute_hysteresis_area(
    up: pd.DataFrame,
    down: pd.DataFrame,
    *,
    x_col: str = "shear_rate_1_s",
    y_col: str = "shear_stress_Pa",
    grid: str = "log",
    n_grid: int = 200,
) -> Tuple[float, str]:
    """
    Compute hysteresis area A = ∫ |τ_up(γ̇)-τ_down(γ̇)| dγ̇
    after interpolating both curves on a common γ̇ grid.
    """
    xu = up[x_col].to_numpy(dtype=float)
    yu = up[y_col].to_numpy(dtype=float)
    xd = down[x_col].to_numpy(dtype=float)
    yd = down[y_col].to_numpy(dtype=float)

    masku = np.isfinite(xu) & np.isfinite(yu) & (xu > 0)
    maskd = np.isfinite(xd) & np.isfinite(yd) & (xd > 0)
    xu, yu = xu[masku], yu[masku]
    xd, yd = xd[maskd], yd[maskd]

    if xu.size < 3 or xd.size < 3:
        return float("nan"), "insufficient_points"

    # Sort for interpolation
    su = np.argsort(xu)
    sd = np.argsort(xd)
    xu, yu = xu[su], yu[su]
    xd, yd = xd[sd], yd[sd]

    xmin = max(float(np.min(xu)), float(np.min(xd)))
    xmax = min(float(np.max(xu)), float(np.max(xd)))
    if not (np.isfinite(xmin) and np.isfinite(xmax) and xmax > xmin > 0):
        return float("nan"), "no_overlap"

    if grid == "log":
        xs = np.logspace(np.log10(xmin), np.log10(xmax), n_grid)
        method = "interp_log_grid_trapz_dgamma"
    else:
        xs = np.linspace(xmin, xmax, n_grid)
        method = "interp_linear_grid_trapz_dgamma"

    yu_i = np.interp(xs, xu, yu)
    yd_i = np.interp(xs, xd, yd)

    area = float(np.trapezoid(np.abs(yu_i - yd_i), xs))
    return area, method


def compute_partial_yield(
    df: pd.DataFrame,
    tauy_Pa: float,
    r1_m: float,
    r2_m: float,
    *,
    tau1_col: str = "shear_stress_Pa",
) -> Tuple[float, np.ndarray, np.ndarray]:
    """
    Return (tau1c_Pa, r0_over_r2, partial_mask)

    tau1c = tauy*(r2/r1)^2
    partial if tau1 < tau1c

    r0 = min(r2, r1*sqrt(tau1/tauy))
    """
    tau1 = df[tau1_col].to_numpy(dtype=float)
    tau1c = float(tauy_Pa) * (float(r2_m) / float(r1_m)) ** 2

    r0_over_r2 = np.full_like(tau1, np.nan, dtype=float)
    partial = np.full_like(tau1, False, dtype=bool)

    if not (np.isfinite(tau1c) and tau1c > 0 and np.isfinite(tauy_Pa) and tauy_Pa > 0):
        return float("nan"), r0_over_r2, partial

    partial = (tau1 < tau1c) & np.isfinite(tau1)

    # r0/r2
    with np.errstate(invalid="ignore", divide="ignore"):
        r0 = float(r1_m) * np.sqrt(tau1 / float(tauy_Pa))
    r0 = np.minimum(r0, float(r2_m))
    r0_over_r2 = r0 / float(r2_m)
    return tau1c, r0_over_r2, partial


# ----------------------------
# Plotting
# ----------------------------

def _maybe_log_axes(ax, x: np.ndarray, y: Optional[np.ndarray] = None, *, xlog: bool = True, ylog: bool = False) -> None:
    """Apply log scaling if data are compatible.

    Rheometer exports often contain NaNs (e.g., unused columns, warm-up rows).
    For axis scaling we treat NaNs as missing values and only require that there
    exist *some* finite values and that the finite minimum is strictly positive.
    """

    # IMPORTANT:
    # Many rheometer exports contain *some* 0 values (e.g., pre-run rows).
    # Using nanmin over all finite values would then block log scaling.
    # Here we decide compatibility based on the existence of at least one
    # strictly-positive finite value.

    x = np.asarray(x, dtype=float)
    if xlog:
        fx = np.isfinite(x) & (x > 0)
        if np.any(fx):
            ax.set_xscale("log")

    if y is not None and ylog:
        y = np.asarray(y, dtype=float)
        fy = np.isfinite(y) & (y > 0)
        if np.any(fy):
            ax.set_yscale("log")




def _is_finite_positive(x: Any) -> bool:
    try:
        return bool(np.isfinite(float(x)) and float(x) > 0)
    except Exception:
        return False


def _clean_positive_xy(x: np.ndarray, y: np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
    """Return finite, positive x/y arrays sorted by x."""
    x = np.asarray(x, dtype=float)
    y = np.asarray(y, dtype=float)
    mask = np.isfinite(x) & np.isfinite(y) & (x > 0) & (y > 0)
    x = x[mask]
    y = y[mask]
    if x.size == 0:
        return x, y
    order = np.argsort(x)
    x = x[order]
    y = y[order]
    # collapse repeated x values so model overlay and axes behave cleanly
    tmp = pd.DataFrame({"x": x, "y": y}).groupby("x", as_index=False).mean()
    return tmp["x"].to_numpy(dtype=float), tmp["y"].to_numpy(dtype=float)


def _hb_eta_from_tau(tau: np.ndarray, tau_y: float, K: float, n: float) -> np.ndarray:
    """Convert HB stress-rate fit to apparent viscosity vs stress.

    HB is fitted as τ = τy + K γ̇^n. To overlay it on an η-vs-τ plot:
      γ̇ = ((τ-τy)/K)^(1/n), η = τ/γ̇, only for τ > τy.
    """
    tau = np.asarray(tau, dtype=float)
    out = np.full_like(tau, np.nan, dtype=float)
    if not (_is_finite_positive(K) and _is_finite_positive(n) and np.isfinite(float(tau_y))):
        return out
    tau_y = max(float(tau_y), 0.0)
    mask = tau > tau_y
    if not np.any(mask):
        return out
    gamma = np.power((tau[mask] - tau_y) / float(K), 1.0 / float(n))
    out[mask] = tau[mask] / gamma
    return out


def _make_model_fit_figures(
    *,
    segments: Dict[str, pd.DataFrame],
    outdir: Path,
    exp_label: str,
    fit_params: Optional[Dict[str, Dict[str, Dict[str, float]]]],
) -> Dict[str, str]:
    """Generate fit-overlay figures for HB, Cross and Ellis.

    Fig5: HB fit on τ vs γ̇.
    Fig6: article-style comparison on η vs τ, showing measured data plus
          HB-transformed viscosity, Cross and Ellis fits.
    """
    artifacts: Dict[str, str] = {}
    if not fit_params:
        return artifacts

    # Fig5: HB overlay on tau vs gamma_dot
    fig, ax = plt.subplots()
    plotted = False
    for seg, d in segments.items():
        g, tau = _clean_positive_xy(d.get("shear_rate_1_s", pd.Series(dtype=float)).to_numpy(dtype=float),
                                    d.get("shear_stress_Pa", pd.Series(dtype=float)).to_numpy(dtype=float))
        if g.size == 0:
            continue
        plotted = True
        ax.plot(g, tau, marker="o", linestyle="None", markersize=4.0, label=f"{seg} data")
        hb = fit_params.get(seg, {}).get("herschel_bulkley", {})
        tau_y = hb.get("tau_y_Pa", np.nan)
        K = hb.get("K", np.nan)
        n = hb.get("n", np.nan)
        if _is_finite_positive(K) and _is_finite_positive(n) and np.isfinite(float(tau_y)):
            gf = np.logspace(np.log10(np.min(g)), np.log10(np.max(g)), 240)
            tf = _hb_model(gf, max(float(tau_y), 0.0), float(K), float(n))
            ax.plot(gf, tf, linestyle="-", linewidth=1.6,
                    label=f"{seg} HB fit: τy={float(tau_y):.4g} Pa")
    if plotted:
        ax.set_xscale("log")
        ax.set_yscale("log")
        ax.set_xlabel("Shear rate γ̇ (1/s)")
        ax.set_ylabel("Shear stress τ (Pa)")
        ax.set_title(f"Fig5 HB fit: τ vs γ̇ — {exp_label}")
        ax.legend(fontsize=8)
    else:
        ax.text(0.5, 0.5, "No valid positive τ-γ̇ data for HB overlay.", ha="center", va="center", transform=ax.transAxes)
    fp = outdir / "fig5_hb_fit_tau_vs_gammadot.png"
    fig.tight_layout()
    fig.savefig(fp, dpi=220)
    plt.close(fig)
    artifacts["fig5"] = str(fp)

    # Fig6: all three models on eta vs tau, similar to Stokes & Telford Fig. 2
    fig, ax = plt.subplots()
    plotted = False
    for seg, d in segments.items():
        tau, eta = _clean_positive_xy(d.get("shear_stress_Pa", pd.Series(dtype=float)).to_numpy(dtype=float),
                                      d.get("viscosity_Pa_s", pd.Series(dtype=float)).to_numpy(dtype=float))
        if tau.size == 0:
            continue
        plotted = True
        ax.plot(tau, eta, marker="o", linestyle="None", markersize=4.0, label=f"{seg} data")
        tf = np.logspace(np.log10(np.min(tau)), np.log10(np.max(tau)), 300)
        params_by_model = fit_params.get(seg, {})

        hb = params_by_model.get("herschel_bulkley", {})
        tau_y = hb.get("tau_y_Pa", np.nan)
        K = hb.get("K", np.nan)
        n = hb.get("n", np.nan)
        if _is_finite_positive(K) and _is_finite_positive(n) and np.isfinite(float(tau_y)):
            eta_hb = _hb_eta_from_tau(tf, float(tau_y), float(K), float(n))
            valid = np.isfinite(eta_hb) & (eta_hb > 0)
            if np.any(valid):
                ax.plot(tf[valid], eta_hb[valid], linestyle="--", linewidth=1.4,
                        label=f"{seg} HB → η(τ), τy={float(tau_y):.4g} Pa")

        cross = params_by_model.get("cross", {})
        eta0 = cross.get("eta0_Pa_s", np.nan)
        eta_inf = cross.get("eta_inf_Pa_s", np.nan)
        sigma_c = cross.get("sigma_c_Pa", np.nan)
        m = cross.get("m", np.nan)
        if _is_finite_positive(eta0) and np.isfinite(float(eta_inf)) and _is_finite_positive(sigma_c) and _is_finite_positive(m):
            delta = max(float(eta0) - float(eta_inf), 0.0)
            yf = _cross_model_tau_eta(tf, float(eta_inf), delta, float(sigma_c), float(m))
            ax.plot(tf, yf, linestyle="-", linewidth=1.5,
                    label=f"{seg} Cross, σc={float(sigma_c):.4g} Pa")
            if np.min(tf) <= float(sigma_c) <= np.max(tf):
                ax.axvline(float(sigma_c), linestyle=":", linewidth=0.9)

        ellis = params_by_model.get("ellis", {})
        eta0_e = ellis.get("eta0_Pa_s", np.nan)
        sigma_c_e = ellis.get("sigma_c_Pa", np.nan)
        m_e = ellis.get("m", np.nan)
        if _is_finite_positive(eta0_e) and _is_finite_positive(sigma_c_e) and _is_finite_positive(m_e):
            yf = _ellis_model_tau_eta(tf, float(eta0_e), float(sigma_c_e), float(m_e))
            ax.plot(tf, yf, linestyle="-.", linewidth=1.5,
                    label=f"{seg} Ellis, σc={float(sigma_c_e):.4g} Pa")
            if np.min(tf) <= float(sigma_c_e) <= np.max(tf):
                ax.axvline(float(sigma_c_e), linestyle=":", linewidth=0.9)

    if plotted:
        ax.set_xscale("log")
        ax.set_yscale("log")
        ax.set_xlabel("Shear stress τ (Pa)")
        ax.set_ylabel("Apparent viscosity η (Pa·s)")
        ax.set_title(f"Fig6 HB / Cross / Ellis comparison: η vs τ — {exp_label}")
        ax.legend(fontsize=7)
    else:
        ax.text(0.5, 0.5, "No valid positive η-τ data for model comparison.", ha="center", va="center", transform=ax.transAxes)
    fp = outdir / "fig6_model_comparison_eta_vs_tau.png"
    fig.tight_layout()
    fig.savefig(fp, dpi=220)
    plt.close(fig)
    artifacts["fig6"] = str(fp)

    return artifacts

def make_plots(
    *,
    df_all: pd.DataFrame,
    segments: Dict[str, pd.DataFrame],
    outdir: str | Path,
    exp_label: str,
    partial_info: Optional[Dict[str, Dict[str, Any]]] = None,
    fit_params: Optional[Dict[str, Dict[str, Dict[str, float]]]] = None,
) -> Dict[str, str]:
    """
    Create figures. Returns dict kind->filepath.

    partial_info can contain per-segment:
      {
        "up": {"tau1c":..., "partial_mask":..., "r0_over_r2":...},
        "down": {...},
        "all": {...}
      }

    fit_params can contain per-segment model parameters:
      {
        "up": {"herschel_bulkley": {...}, "cross": {...}, "ellis": {...}},
        "down": {...}
      }
    """
    outdir = Path(outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    artifacts: Dict[str, str] = {}

    # Fig1: shear rate vs shear stress (raw data as points only)
    fig, ax = plt.subplots()
    for seg, d in segments.items():
        ax.plot(
            d["shear_rate_1_s"],
            d["shear_stress_Pa"],
            marker="o",
            linestyle="None",
            markersize=4.5,
            label=seg,
        )
    _maybe_log_axes(ax, df_all["shear_rate_1_s"].to_numpy(), df_all["shear_stress_Pa"].to_numpy(), xlog=True, ylog=True)
    ax.set_xlabel("Shear rate γ̇ (1/s)")
    ax.set_ylabel("Shear stress τ (Pa)")
    ax.set_title(f"Fig1 τ vs γ̇ — {exp_label}")
    ax.legend()
    fp = outdir / "fig1_tau_vs_gammadot.png"
    fig.tight_layout()
    fig.savefig(fp, dpi=200)
    plt.close(fig)
    artifacts["fig1"] = str(fp)

    # Fig2: shear rate vs viscosity (raw data as points only)
    fig, ax = plt.subplots()
    for seg, d in segments.items():
        ax.plot(
            d["shear_rate_1_s"],
            d["viscosity_Pa_s"],
            marker="o",
            linestyle="None",
            markersize=4.5,
            label=seg,
        )
    _maybe_log_axes(ax, df_all["shear_rate_1_s"].to_numpy(), df_all["viscosity_Pa_s"].to_numpy(), xlog=True, ylog=True)
    ax.set_xlabel("Shear rate γ̇ (1/s)")
    ax.set_ylabel("Viscosity η (Pa·s)")
    ax.set_title(f"Fig2 η vs γ̇ — {exp_label}")
    ax.legend()
    fp = outdir / "fig2_eta_vs_gammadot.png"
    fig.tight_layout()
    fig.savefig(fp, dpi=200)
    plt.close(fig)
    artifacts["fig2"] = str(fp)

    # Fig3: shear rate vs shear stress + partial yield compatibility markers
    fig, ax = plt.subplots()
    for seg, d in segments.items():
        if partial_info and seg in partial_info and np.isfinite(partial_info[seg].get("tau1c", np.nan)):
            m = partial_info[seg]["partial_mask"]
            ax.plot(
                d["shear_rate_1_s"].to_numpy()[~m],
                d["shear_stress_Pa"].to_numpy()[~m],
                marker="o",
                linestyle="None",
                markersize=4.5,
                label=f"{seg} (τ1≥τ1,c)",
            )
            ax.plot(
                d["shear_rate_1_s"].to_numpy()[m],
                d["shear_stress_Pa"].to_numpy()[m],
                marker="x",
                linestyle="None",
                markersize=5.0,
                label=f"{seg} (τ1<τ1,c)",
            )
            ax.axhline(partial_info[seg]["tau1c"], linestyle="--", linewidth=1)
        else:
            ax.plot(
                d["shear_rate_1_s"],
                d["shear_stress_Pa"],
                marker="o",
                linestyle="None",
                markersize=4.5,
                label=seg,
            )

    _maybe_log_axes(ax, df_all["shear_rate_1_s"].to_numpy(), df_all["shear_stress_Pa"].to_numpy(), xlog=True, ylog=True)
    ax.set_xlabel("Shear rate γ̇ (1/s)")
    ax.set_ylabel("Shear stress τ (Pa)")
    ax.set_title(f"Fig3 τ vs γ̇ + partial-yield check — {exp_label}")
    ax.legend()
    fp = outdir / "fig3_partial_yield_band.png"
    fig.tight_layout()
    fig.savefig(fp, dpi=200)
    plt.close(fig)
    artifacts["fig3"] = str(fp)

    # Fig4: r0/r2 vs shear rate (points only)
    fig, ax = plt.subplots()
    plotted_any = False
    for seg, d in segments.items():
        if partial_info and seg in partial_info:
            r0r2 = partial_info[seg].get("r0_over_r2", None)
            if r0r2 is not None:
                ax.plot(
                    d["shear_rate_1_s"],
                    r0r2,
                    marker="o",
                    linestyle="None",
                    markersize=4.5,
                    label=seg,
                )
                plotted_any = True

    if not plotted_any:
        ax.text(0.5, 0.5, "Fig4 requires r1,r2 and fitted τy (HB).", ha="center", va="center", transform=ax.transAxes)
    else:
        _maybe_log_axes(ax, df_all["shear_rate_1_s"].to_numpy(), None, xlog=True, ylog=False)
        ax.set_ylim(0.0, 1.05)
        ax.set_xlabel("Shear rate γ̇ (1/s)")
        ax.set_ylabel("r0/r2 (yielded radius / cup radius)")
        ax.set_title(f"Fig4 r0/r2 vs γ̇ — {exp_label}")
        ax.legend()

    fp = outdir / "fig4_r0_over_r2.png"
    fig.tight_layout()
    fig.savefig(fp, dpi=200)
    plt.close(fig)
    artifacts["fig4"] = str(fp)

    # Fig5 / Fig6: model fit overlays so users can visually inspect why
    # HB, Cross and Ellis give different apparent yield/critical stresses.
    artifacts.update(_make_model_fit_figures(segments=segments, outdir=outdir, exp_label=exp_label, fit_params=fit_params))

    return artifacts


def make_geometry_schematic(
    geometry: str,
    r1_m: float,
    r2_m: float,
    *,
    title: str | None = None,
):
    """Create an illustrative concentric-geometry schematic for vane/cup or bob/cup.

    The drawing is scaled by the actual ratio r1/r2 and adds radius annotations,
    gap annotation, and a lightly shaded annulus so the geometry reads clearly
    inside the Streamlit UI.
    """
    if not (np.isfinite(r1_m) and np.isfinite(r2_m) and r1_m > 0 and r2_m > 0 and r2_m > r1_m):
        raise ValueError("Need valid radii with r2 > r1.")

    ratio = float(r1_m) / float(r2_m)
    r1_mm = float(r1_m) * 1000.0
    r2_mm = float(r2_m) * 1000.0
    gap_mm = (float(r2_m) - float(r1_m)) * 1000.0

    fig, ax = plt.subplots(figsize=(5.2, 5.2))
    ax.set_aspect("equal")
    ax.axis("off")

    # Outer cup wall
    outer = Circle((0.0, 0.0), 1.0, fill=False, linewidth=3.0)
    ax.add_patch(outer)
    # Annulus shading to make the gap easier to read visually
    annulus = Wedge((0.0, 0.0), 1.0, 0, 360, width=max(0.02, 1.0 - ratio), alpha=0.12)
    ax.add_patch(annulus)
    # Inner bob / vane envelope
    inner = Circle((0.0, 0.0), ratio, fill=True, alpha=0.18, linewidth=2.2)
    ax.add_patch(inner)
    inner_outline = Circle((0.0, 0.0), ratio, fill=False, linewidth=2.2)
    ax.add_patch(inner_outline)

    if geometry == "vane_cup":
        # Add simple spokes so the vane looks less like a plain cylinder.
        n_spokes = 8
        for ang in np.linspace(0, 2 * np.pi, n_spokes, endpoint=False):
            ax.plot([0.0, ratio * np.cos(ang)], [0.0, ratio * np.sin(ang)], linewidth=1.2)
        hub = Circle((0.0, 0.0), ratio * 0.16, fill=False, linewidth=1.2)
        ax.add_patch(hub)
        inner_label = "vane"
    else:
        inner_label = "bob"

    # Radius arrows and labels
    ang_r1 = np.deg2rad(35)
    ang_r2 = np.deg2rad(140)
    p1 = (ratio * np.cos(ang_r1), ratio * np.sin(ang_r1))
    p2 = (1.0 * np.cos(ang_r2), 1.0 * np.sin(ang_r2))
    ax.add_patch(FancyArrowPatch((0.0, 0.0), p1, arrowstyle="<->", mutation_scale=14, linewidth=1.3))
    ax.add_patch(FancyArrowPatch((0.0, 0.0), p2, arrowstyle="<->", mutation_scale=14, linewidth=1.3))
    ax.text(p1[0] * 0.62, p1[1] * 0.62 + 0.06, f"r1 = {r1_mm:.2f} mm", ha="center", va="center")
    ax.text(p2[0] * 0.66 - 0.03, p2[1] * 0.66 + 0.04, f"r2 = {r2_mm:.2f} mm", ha="center", va="center")

    # Gap annotation
    y_gap = -1.10
    ax.add_patch(FancyArrowPatch((ratio, y_gap), (1.0, y_gap), arrowstyle="<->", mutation_scale=14, linewidth=1.2))
    ax.text((ratio + 1.0) / 2.0, y_gap - 0.08, f"gap = {gap_mm:.2f} mm", ha="center", va="top")

    # Labels
    ax.text(0.0, 0.0, inner_label, ha="center", va="center")
    ax.text(0.0, 1.08, "cup wall", ha="center", va="bottom")
    ax.text(0.0, -1.28, f"r2 / r1 = {float(r2_m) / float(r1_m):.3f}", ha="center", va="top")

    ax.set_xlim(-1.35, 1.35)
    ax.set_ylim(-1.35, 1.35)
    if title:
        ax.set_title(title)
    return fig


# ----------------------------
# Analysis pipeline
# ----------------------------

def _insert_fit_result(conn: sqlite3.Connection, experiment_id: int, segment: str, model: str, fields: Dict[str, Any], method: str = "") -> None:
    _ensure_fit_results_columns(conn)
    cur = conn.cursor()
    cur.execute(
        """
        INSERT INTO fit_results(
            experiment_id, segment, model,
            tau_y_Pa, K, n,
            eta0_Pa_s, eta_inf_Pa_s, sigma_c_Pa, m,
            r_squared, n_points, method
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        (
            experiment_id,
            segment,
            model,
            fields.get("tau_y_Pa", None),
            fields.get("K", None),
            fields.get("n", None),
            fields.get("eta0_Pa_s", None),
            fields.get("eta_inf_Pa_s", None),
            fields.get("sigma_c_Pa", None),
            fields.get("m", None),
            fields.get("r_squared", None),
            fields.get("n_points", None),
            method,
        ),
    )


def _upsert_derived_metrics(conn: sqlite3.Connection, experiment_id: int, metrics: Dict[str, Any]) -> None:
    cur = conn.cursor()
    # delete then insert (simple upsert)
    cur.execute("DELETE FROM derived_metrics WHERE experiment_id=?", (experiment_id,))
    cur.execute(
        """
        INSERT INTO derived_metrics(
            experiment_id,
            hysteresis_area_Pa_s, hysteresis_area_method,
            tau1c_up_Pa, tau1c_down_Pa, tau1c_all_Pa,
            tauy_up_Pa, tauy_down_Pa, tauy_all_Pa
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        (
            experiment_id,
            metrics.get("hysteresis_area_Pa_s", None),
            metrics.get("hysteresis_area_method", None),
            metrics.get("tau1c_up_Pa", None),
            metrics.get("tau1c_down_Pa", None),
            metrics.get("tau1c_all_Pa", None),
            metrics.get("tauy_up_Pa", None),
            metrics.get("tauy_down_Pa", None),
            metrics.get("tauy_all_Pa", None),
        ),
    )


def _insert_artifact(conn: sqlite3.Connection, experiment_id: int, kind: str, path: str) -> None:
    cur = conn.cursor()
    cur.execute(
        "INSERT INTO artifacts(experiment_id, kind, path) VALUES (?, ?, ?)",
        (experiment_id, kind, path),
    )


def analyze_experiment(
    db_path: str | Path,
    experiment_id: int,
    *,
    outdir: str | Path,
) -> Dict[str, Any]:
    """
    Full analysis:
    - load data
    - detect up/down
    - fit HB, Cross and Ellis models
    - compute hysteresis area
    - compute tau1c and r0/r2 using HB τy and (r1,r2)
    - generate plots
    - store results + artifact paths in DB

    Returns a dict summary (also written to CSV).
    """
    conn = connect(db_path)
    try:
        exp = fetch_experiment(conn, experiment_id)
        df = load_measurements_df(conn, experiment_id)
        segments = split_up_down(df)

        # Write segments back to DB (for browsing)
        seg_by_idx: Dict[int, str] = {}
        if "all" in segments:
            for i in segments["all"]["row_index"].astype(int).tolist():
                seg_by_idx[int(i)] = "all"
        else:
            for seg_name, sdf in segments.items():
                for i in sdf["row_index"].astype(int).tolist():
                    seg_by_idx[int(i)] = seg_name
        update_segments(conn, experiment_id, seg_by_idx)

        # Clear prior fits/artifacts for this experiment (optional)
        conn.execute("DELETE FROM fit_results WHERE experiment_id=?", (experiment_id,))
        conn.execute("DELETE FROM artifacts WHERE experiment_id=?", (experiment_id,))
        conn.execute("DELETE FROM derived_metrics WHERE experiment_id=?", (experiment_id,))

        # Fits
        fit_rows: List[Dict[str, Any]] = []
        hb_tauy_by_seg: Dict[str, float] = {}
        fit_params_by_seg: Dict[str, Dict[str, Dict[str, float]]] = {}

        for seg_name, sdf in segments.items():
            fit_params_by_seg.setdefault(seg_name, {})
            gamma = sdf["shear_rate_1_s"].to_numpy(dtype=float)
            tau = sdf["shear_stress_Pa"].to_numpy(dtype=float)
            eta = sdf["viscosity_Pa_s"].to_numpy(dtype=float)

            # Herschel–Bulkley: τ = τy + K γ̇^n
            hb = fit_herschel_bulkley(gamma, tau, tauy0=exp.get("yield_stress0_Pa", None))
            _insert_fit_result(conn, experiment_id, seg_name, "herschel_bulkley", hb, method="curve_fit_tau_vs_gammadot")
            fit_rows.append({"segment": seg_name, "model": "herschel_bulkley", **hb})
            hb_tauy_by_seg[seg_name] = hb["tau_y_Pa"]
            fit_params_by_seg[seg_name]["herschel_bulkley"] = hb

            # Cross: η = η∞ + (η0-η∞)/(1+(τ/σc)^m)
            cross = fit_cross(tau, eta)
            _insert_fit_result(conn, experiment_id, seg_name, "cross", cross, method="curve_fit_log_eta_vs_tau")
            fit_rows.append({"segment": seg_name, "model": "cross", **cross})
            fit_params_by_seg[seg_name]["cross"] = cross

            # Ellis: η = η0/(1+(τ/σc)^m)
            ellis = fit_ellis(tau, eta)
            _insert_fit_result(conn, experiment_id, seg_name, "ellis", ellis, method="curve_fit_log_eta_vs_tau")
            fit_rows.append({"segment": seg_name, "model": "ellis", **ellis})
            fit_params_by_seg[seg_name]["ellis"] = ellis

        # Hysteresis area (if up/down)
        hysteresis_area = float("nan")
        hysteresis_method = ""
        if "up" in segments and "down" in segments:
            hysteresis_area, hysteresis_method = compute_hysteresis_area(segments["up"], segments["down"])
        # Partial yield metrics
        r1 = exp.get("r1_m", None)
        r2 = exp.get("r2_m", None)

        partial_info: Dict[str, Dict[str, Any]] = {}
        derived: Dict[str, Any] = {
            "hysteresis_area_Pa_s": hysteresis_area,
            "hysteresis_area_method": hysteresis_method,
        }

        if r1 is not None and r2 is not None and np.isfinite(r1) and np.isfinite(r2) and r1 > 0 and r2 > 0:
            for seg_name, sdf in segments.items():
                tauy = hb_tauy_by_seg.get(seg_name, float("nan"))
                tau1c, r0r2, mask = compute_partial_yield(sdf, tauy, float(r1), float(r2))
                partial_info[seg_name] = {"tau1c": tau1c, "r0_over_r2": r0r2, "partial_mask": mask}
                if seg_name == "up":
                    derived["tau1c_up_Pa"] = tau1c
                    derived["tauy_up_Pa"] = tauy
                elif seg_name == "down":
                    derived["tau1c_down_Pa"] = tau1c
                    derived["tauy_down_Pa"] = tauy
                elif seg_name == "all":
                    derived["tau1c_all_Pa"] = tau1c
                    derived["tauy_all_Pa"] = tauy

        _upsert_derived_metrics(conn, experiment_id, derived)

        # Plots
        exp_label = f"exp{experiment_id} — {exp['sample_name']}"
        artifacts = make_plots(
            df_all=df,
            segments=segments,
            outdir=outdir,
            exp_label=exp_label,
            partial_info=partial_info,
            fit_params=fit_params_by_seg,
        )

        for kind, path in artifacts.items():
            _insert_artifact(conn, experiment_id, kind, path)

        # Summary CSV
        outdir = Path(outdir)
        outdir.mkdir(parents=True, exist_ok=True)
        summary_df = pd.DataFrame(fit_rows)
        preferred_cols = [
            "segment", "model",
            "tau_y_Pa", "K", "n",
            "eta0_Pa_s", "eta_inf_Pa_s", "sigma_c_Pa", "m",
            "r_squared", "n_points",
        ]
        summary_df = summary_df[[c for c in preferred_cols if c in summary_df.columns]]
        summary_csv = outdir / "fit_summary.csv"
        summary_df.to_csv(summary_csv, index=False)
        _insert_artifact(conn, experiment_id, "summary_csv", str(summary_csv))

        # A single "overview" Excel file: fits + derived metrics (incl. hysteresis area, tau1c, tauy)
        overview_xlsx = outdir / "results_overview.xlsx"
        derived_df = pd.DataFrame([derived])
        with pd.ExcelWriter(overview_xlsx, engine="openpyxl") as xw:
            summary_df.to_excel(xw, sheet_name="fit_results", index=False)
            derived_df.to_excel(xw, sheet_name="derived_metrics", index=False)
        _insert_artifact(conn, experiment_id, "overview_xlsx", str(overview_xlsx))

        conn.commit()

        return {
            "experiment": exp,
            "derived_metrics": derived,
            "fit_summary_csv": str(summary_csv),
            "artifacts": artifacts,
        }
    finally:
        conn.close()

# ----------------------------
# Convenience queries for the Streamlit UI
# ----------------------------

def list_experiments_df(db_path: str | Path) -> pd.DataFrame:
    """Return a DataFrame of experiments (most recent first)."""
    db_path = Path(db_path)
    if not db_path.exists():
        return pd.DataFrame(columns=["id","sample_name","geometry","gap_m","r1_m","r2_m","yield_stress0_Pa","created_at","notes"])
    conn = connect(db_path)
    try:
        return pd.read_sql_query(
            """
            SELECT id, sample_name, geometry, gap_m, r1_m, r2_m, yield_stress0_Pa, created_at, notes
            FROM experiments
            ORDER BY id DESC
            """,
            conn,
        )
    finally:
        conn.close()


def update_experiment_meta(
    db_path: str | Path,
    experiment_id: int,
    *,
    sample_name: str,
    geometry: str,
    gap_m: Optional[float] = None,
    r1_m: Optional[float] = None,
    r2_m: Optional[float] = None,
    yield_stress0_Pa: Optional[float] = None,
    notes: Optional[str] = None,
) -> None:
    """Update experiment metadata (helper for Streamlit UI)."""
    db_path = Path(db_path)
    if not db_path.exists():
        raise FileNotFoundError(db_path)
    conn = connect(db_path)
    try:
        update_experiment(
            conn,
            int(experiment_id),
            sample_name=sample_name,
            geometry=geometry,
            gap_m=gap_m,
            r1_m=r1_m,
            r2_m=r2_m,
            yield_stress0_Pa=yield_stress0_Pa,
            notes=notes,
        )
        conn.commit()
    finally:
        conn.close()


def fit_results_df(db_path: str | Path, experiment_id: int) -> pd.DataFrame:
    db_path = Path(db_path)
    if not db_path.exists():
        return pd.DataFrame()
    conn = connect(db_path)
    try:
        return pd.read_sql_query(
            """
            SELECT segment, model, tau_y_Pa, K, n, eta0_Pa_s, eta_inf_Pa_s, sigma_c_Pa, m, r_squared, n_points, method, created_at
            FROM fit_results
            WHERE experiment_id=?
            ORDER BY segment, model
            """,
            conn,
            params=(experiment_id,),
        )
    finally:
        conn.close()


def derived_metrics_df(db_path: str | Path, experiment_id: int) -> pd.DataFrame:
    db_path = Path(db_path)
    if not db_path.exists():
        return pd.DataFrame()
    conn = connect(db_path)
    try:
        df = pd.read_sql_query(
            """
            SELECT hysteresis_area_Pa_s, hysteresis_area_method,
                   tau1c_up_Pa, tau1c_down_Pa, tau1c_all_Pa,
                   tauy_up_Pa, tauy_down_Pa, tauy_all_Pa,
                   created_at
            FROM derived_metrics
            WHERE experiment_id=?
            """,
            conn,
            params=(experiment_id,),
        )
        return df
    finally:
        conn.close()


def artifacts_df(db_path: str | Path, experiment_id: int) -> pd.DataFrame:
    db_path = Path(db_path)
    if not db_path.exists():
        return pd.DataFrame()
    conn = connect(db_path)
    try:
        return pd.read_sql_query(
            """
            SELECT kind, path, created_at
            FROM artifacts
            WHERE experiment_id=?
            ORDER BY created_at DESC
            """,
            conn,
            params=(experiment_id,),
        )
    finally:
        conn.close()


def measurements_df(db_path: str | Path, experiment_id: int) -> pd.DataFrame:
    db_path = Path(db_path)
    if not db_path.exists():
        return pd.DataFrame()
    conn = connect(db_path)
    try:
        return load_measurements_df(conn, experiment_id)
    finally:
        conn.close()


def delete_experiment(db_path: str | Path, experiment_id: int) -> None:
    """Delete an experiment and all dependent rows.

    Thanks to ON DELETE CASCADE constraints, this will automatically remove:
    - measurements
    - fit_results
    - derived_metrics
    - artifacts

    Note: this only deletes database rows. Any files on disk (outputs/, uploads/)
    are not removed here; the Streamlit UI can optionally clean them up.
    """
    db_path = Path(db_path)
    if not db_path.exists():
        raise FileNotFoundError(db_path)
    conn = connect(db_path)
    try:
        cur = conn.cursor()
        cur.execute("DELETE FROM experiments WHERE id=?", (int(experiment_id),))
        conn.commit()
    finally:
        conn.close()


def delete_all_experiments(db_path: str | Path) -> None:
    """Delete ALL experiments (and dependent rows)."""
    db_path = Path(db_path)
    if not db_path.exists():
        raise FileNotFoundError(db_path)
    conn = connect(db_path)
    try:
        conn.execute("DELETE FROM experiments")
        conn.commit()
    finally:
        conn.close()
